version: "3.3"

services: 
    frontend:
        build: ./frontend
        ports: 
            - 5000:5000
            - 35729:35729
        user: node
    
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
            args:
                INSTALL_DEV: ${INSTALL_DEV-false}
        ports: 
            - 5001:80
        command: /start.sh
