version: "3.3"

services: 
  db:
    image: postgres:12
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - .env
    links:
      - "db:pgsql-server"
    ports: 
      - 5050:80
      - 5051:443

  frontend:
    build: ./frontend
    ports: 
      - 5000:5000
      - 35729:35729
    user: node
  
  backend:
    depends_on: 
      - db
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports: 
      - 5001:80
    command: /start.sh
