version: "3.3"

services: 
  db:
    image: postgres:13
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata


  frontend:
    build: ./frontend
    ports: 
      - 5000:5000
      - 35729:35729
    user: node
  
  backend:
    depends_on: 
      - db
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    
    ports: 
      - 5001:80
    command: /start.sh

volumes:
  app-db-data:
