version: "3.3"

services: 
    frontend:
        build: ./frontend
        ports: 
            - 5000:5000
            - 35729:35729
        volumes: 
            - /home/urjeet/projects/tailwind-python-template/frontend/app:/home/node/app
        user: node
    
    backend:
        build: ./backend
        ports: 
            - 5001:80
        volumes: 
            - /home/urjeet/projects/tailwind-python-template/backend/app:/app/
        command: "/start-reload.sh" # this is for dev only change for prod to /start.sh