"""Initial Schema

Revision ID: 2a2d9efe87a8
Revises: 
Create Date: 2020-12-11 16:47:27.143527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a2d9efe87a8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    roles_table = op.create_table(
        "roles", sa.Column("id", sa.Integer(), nullable=False), sa.Column("title", sa.String(), nullable=True), sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_roles_title"), "roles", ["title"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)

    op.bulk_insert(
        roles_table,
        [
            {"id": 1, "title": "Admin"},
            {"id": 2, "title": "Super User"},
            {"id": 3, "title": "User"},
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_title"), table_name="roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
